### ISSUE TITLE
DataType is Different than a Property ?

### ISSUE THREAD

**Issue by sezginakman** [tdietrich513/DataTableProxy#3]
![image](https://user-images.githubusercontent.com/6608122/48625980-be920280-e9c1-11e8-8bea-79302aaf8452.png)

**Comment by tdietrich513** [comment]
I think what's going on here is that a nullable type is a reference type, so DTP calls `ToString` on it, which is by design. I wrote this library before .net had support for nullable types so it doesn't really have any concept on how to deal with them.

I would recommend using `yo => yo.IdLog.Value` IF you can be sure that all your records will have an ID, and if not, `yo => (int)(yo.IdLog ?? -1)`, or something of that nature. What you need to do is coerce it into a value type somehow.

**Comment by sezginakman** [comment]
Thank you for your answer.
Yes I understand than I use like  .AddColumn("Id", yo => yo.IdLog ?? 0).
